stages:
  train:
    cmd: python src/train_baseline.py
    deps:
    - data
    - src/train_baseline.py
    outs:
    - models/baseline

  train_lstm:
    cmd: python src/train_lstm.py
    deps:
    - data/olid-training-v1.0.tsv
    - src/dataset_lstm.py
    - src/model_lstm.py
    - src/train_lstm.py
    params:
    - lstm
    outs:
    - models/lstm

  train_bert:
    cmd: python src/train_bert.py
    deps:
    - data/olid-training-v1.0.tsv
    - src/train_bert.py
    params:
    - bert
    outs:
    - models/bert

  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data
    - models/baseline
    - models/lstm
    - models/bert
    - src/evaluate.py
    - src/model_lstm.py
    - src/dataset_lstm.py
    - src/predict_bert.py
    params:
    - lstm
    - bert
    metrics:
    - reports/metrics.json