stages:
  train:
    cmd: python src/train_baseline.py
    deps:
    - data
    - src/train_baseline.py
    outs:
    - models
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data
    - models
    - src/evaluate.py
    metrics:
    - reports/metrics.json
