stages:
  train:
    cmd: python src/train_baseline.py
    deps:
    - data
    - src/train_baseline.py
    outs:
    - models/baseline
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data
    - models/baseline
    - models/lstm
    - src/evaluate.py
    metrics:
    - reports/metrics.json
  train_lstm:
    cmd: python src/train_lstm.py
    deps:
    - data/olid-training-v1.0.tsv
    - src/dataset_lstm.py
    - src/model_lstm.py
    - src/train_lstm.py
    params:
    - lstm
    outs:
    - models/lstm
