name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run code quality check
        run: |
          pip install flake8
          flake8 src/ --max-line-length=120 --ignore=E402,W503,E221,E241,E225,W292,E123,E125,F401,E741,E265,E302,E501

      - name: Run tests
        run: python src/test.py